services:
  koa-app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    # environment:
    #   - PORT=${PORT}
    #   - COMMANDS_PATH=${COMMANDS_PATH}
    restart: unless-stopped
    volumes:
      - ./commands.json:${COMMANDS_PATH}