services:
  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    #   - REACT_APP_API_URL=http://localhost:8000
    
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "4000:4000"
      
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env
    #   - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: randompassword
    volumes:
      - ${PWD}/mongo/data:/data/db
      - ${PWD}/mongo/dumps:/data/dumps
    command: ["--auth"]